GPP = g++

WORKSPACE_FOLDER = /Users/xiangyutong/Documents/数值分析与算法/assignments/ass02/
STD = -std=c++17

SRCS = sinx_numerical.cpp
PROG = sinx_numerical

$(PROG):$(SRCS)
	$(GPP) $(STD) $(SRCS) -o $(PROG)